# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Fabric / Minecraft
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.4

# Fabric API
fabric_version=0.141.3+1.21.11

# Mod
mod_version=2.1.5-(1.21.11)
maven_group=dev.sirblambo
archives_base_name=Impactful

# Dependencies
modmenu_version=17.0.0-beta.2